module.exports = {
  up: queryInterface =>
    queryInterface.bulkInsert("Clients", [
      {
        firstname: "Enock",
        lastname: "Olasi",
        email: "enock.olasi@andela.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Ruth",
        lastname: "Wabwire",
        email: "ruth.wabwire@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Martin",
        lastname: "Luther",
        email: "martin.luther@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Betty",
        lastname: "Mutei",
        email: "betty.kyalo@finlo.ai",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Henry",
        lastname: "Desagu",
        email: "henry.desagu@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Erick",
        lastname: "Kimani",
        email: "erick.kimani@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Marverick",
        lastname: "Essien",
        email: "marverickessien@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Black",
        lastname: "Widow",
        email: "black.widow@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Sandra",
        lastname: "Locoh",
        email: "sandra.locoh@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Nikola",
        lastname: "Tesla",
        email: "nikola.tesla@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Elon",
        lastname: "Musk",
        email: "elon.musk@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Tim",
        lastname: "Cook",
        email: "tim.cook@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Richie",
        lastname: "Spice",
        email: "richie.spice@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Paul",
        lastname: "Soko",
        email: "paul.soko@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Dennis",
        lastname: "Mungai",
        email: "dennis.mungai@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      },
      {
        firstname: "Alice",
        lastname: "Wonder",
        email: "alice.wonder@gmail.com",
        password: "secret",
        preQualified: false,
        qualified: false,
        dateApproved: null,
        isActive: false,
        accountingSoftware: null,
        createdAt: "2019-12-21T17:25:40.103Z",
        updatedAt: "2019-12-21T17:25:40.103Z"
      }
    ]),

  down: queryInterface => queryInterface.bulkDelete("Clients")
};
